import { addIcon } from "@iconify/vue/dist/offline";

/**
 * 这里存放本地图标，在 src/layout/index.vue 文件中加载，避免在首启动加载
 */
import UbuntuFill from "@iconify-icons/ri/ubuntu-fill";
import Menu from "@iconify-icons/ep/menu";
import Edit from "@iconify-icons/ep/edit";
import InformationLine from "@iconify-icons/ri/information-line";
import SetUp from "@iconify-icons/ep/set-up";
import TerminalWindowLine from "@iconify-icons/ri/terminal-window-line";
import Guide from "@iconify-icons/ep/guide";
import HomeFilled from "@iconify-icons/ep/home-filled";
import Card from "@iconify-icons/ri/bank-card-line";
import ListCheck from "@iconify-icons/ri/list-check";
import Histogram from "@iconify-icons/ep/histogram";
import Ppt from "@iconify-icons/ri/file-ppt-2-line";
import CheckboxCircleLine from "@iconify-icons/ri/checkbox-circle-line";
import FlUser from "@iconify-icons/ri/admin-line";
import Role from "@iconify-icons/ri/admin-fill";
import Setting from "@iconify-icons/ri/settings-3-line";
import Dept from "@iconify-icons/ri/git-branch-line";
import Search from "@iconify-icons/ri/search-line";
import Lollipop from "@iconify-icons/ep/lollipop";
import Monitor from "@iconify-icons/ep/monitor";
import Tag from "@iconify-icons/ri/bookmark-2-line";
import Table from "@iconify-icons/ri/table-line";
import Info from "@iconify-icons/ri/file-info-line";
import Artboard from "@iconify-icons/ri/artboard-line";
import FolderOpened from "@iconify-icons/ep/folder-opened";
import EpShare from "@iconify-icons/ep/share";
import EpHistogram from "@iconify-icons/ep/histogram";
import EpManagement from "@iconify-icons/ep/management";
import EpList from "@iconify-icons/ep/list";
import EpDownLoad from "@iconify-icons/ep/document";
import EpMonitor from "@iconify-icons/ep/monitor";
import RiCoinFill from "@iconify-icons/ri/coin-fill";
import RiArticleLine from "@iconify-icons/ri/article-line";
import RiTreeFill from "@iconify-icons/ri/tree-fill";
import RiLandscapeFill from "@iconify-icons/ri/landscape-fill";
import RiGradienterFill from "@iconify-icons/ri/gradienter-fill";
import RiDatabase2Fill from "@iconify-icons/ri/database-2-fill";
import RiHistoryFill from "@iconify-icons/ri/history-fill";
import RiOrderPlayLine from "@iconify-icons/ri/order-play-line";

addIcon("ubuntuFill", UbuntuFill);
addIcon("menu", Menu);
addIcon("edit", Edit);
addIcon("informationLine", InformationLine);
addIcon("setUp", SetUp);
addIcon("terminalWindowLine", TerminalWindowLine);
addIcon("guide", Guide);
addIcon("homeFilled", HomeFilled);
addIcon("card", Card);
addIcon("listCheck", ListCheck);
addIcon("histogram", Histogram);
addIcon("ppt", Ppt);
addIcon("checkboxCircleLine", CheckboxCircleLine);
addIcon("flUser", FlUser);
addIcon("role", Role);
addIcon("setting", Setting);
addIcon("dept", Dept);
addIcon("search", Search);
addIcon("lollipop", Lollipop);
addIcon("monitor", Monitor);
addIcon("tag", Tag);
addIcon("table", Table);
addIcon("info", Info);
addIcon("artboard", Artboard);
addIcon("folderOpen", FolderOpened);
addIcon("share", EpShare);
addIcon("chart", EpHistogram);
addIcon("book", EpManagement);
addIcon("notebook", EpList);
addIcon("download", EpDownLoad);
addIcon("monitor", EpMonitor);
addIcon("soil-type", RiCoinFill);
addIcon("area-info", RiArticleLine);
addIcon("vegetation-coverage", RiTreeFill);
addIcon("terrain-landform", RiLandscapeFill);
addIcon("soil-erosion-grade", RiGradienterFill);
addIcon("monitor-data", RiDatabase2Fill);
addIcon("land-use-change-history", RiHistoryFill);
addIcon("land-management-plans", RiOrderPlayLine);

