server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erosion_watch?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 # 连接池初始化大小
      min-idle: 10 # 最小空闲连接数
      max-active: 20 # 最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: # 访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: ${virtual-host}
      port: 27017
      database: erosion-watch
  rabbitmq:
    host: ${virtual-host}
    port: 5672
    virtual-host: /erosion-watch
    username: erosion
    password: erosion

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /auth/**
      - /**/**

minio:
  endpoint: http://${virtual-host}:9090 #MinIO服务所在地址
  bucket-name: erosion-watch #存储桶名称
  access-key: minioadmin #访问的key
  secret-key: minioadmin #访问的秘钥

virtual-host: 8.140.22.169
