spring:
  application:
    name: erosion-watch-portal
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: ${virtual-host} # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    # SMTP服务器
    host: smtp.qq.com
    # 发送验证码的邮箱（发件人的邮箱）
    username: 2691386627@qq.com
    # 授权码
    password: 123
    # 编码
    default-encoding: utf-8
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用SSL方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connection-timeout: 10000
          # 邮件发送时间的限制，单位毫秒
          write-timeout: 10000

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  token-header: Authorization # JWT存储的请求头
  secret: erosion-portal-secret # JWT加解密使用的密钥
  expiration: 604800 # JWT的超期限时间(60*60*24*7)
  token-head: 'Bearer '  # JWT负载中拿到开头
  expire:
    access-token: 604800
    refresh-token: 2592000 # 设置为一个月

redis:
  database: erosion-watch
  key:
    member: 'member'
    auth-code: 'authCode'
    data: 'data'
    unique-visit: 'uniqueVisit'
    total-visit: 'totalVisit'
    upload-data: 'uploadData'
    process-data: 'processData'
  expire:
    auth-code: 90 # 验证码超时时间
    common: 86400 # 验证码超时时间

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    access-key-id: test # 访问身份验证中用到用户标识
    access-key-secret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucket-name: macro-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    max-size: 10 # 上传文件大小(M)
    callback: http://${virtual-host}/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: erosion-watch/images/ # 上传文件夹路径前缀

mongo:
  insert:
    sqlEnable: true # 用于控制是否通过数据库数据来插入mongo

